import type { Metadata, Viewport } from "next";
import { Space_Grotesk, Inter, JetBrains_Mono, Barlow_Condensed } from "next/font/google";
import { socials } from "@/data/socials";
import "./globals.css";

// Three voices: Space Grotesk 500/600 (all display type: h1-h3, tiles, stats, wordmark),
// Inter (body), JetBrains Mono (ALL meta: labels, years, tags, stats, nav, footer).
const grotesk = Space_Grotesk({ subsets: ["latin"], weight: ["500", "600"], variable: "--font-grotesk", display: "swap" });
const inter = Inter({ subsets: ["latin"], variable: "--font-inter", display: "swap" });
const jetbrains = JetBrains_Mono({ subsets: ["latin"], weight: ["400"], variable: "--font-jetbrains", display: "swap" });
// A separate display voice leaves the cinematic font tokens unchanged.
const headline = Barlow_Condensed({ subsets: ["latin"], weight: ["500", "600"], variable: "--font-headline", display: "swap" });

const SITE = "https://mrvayn.live";
const TITLE = "MrVayn | Unreal Engine & Full-Stack Developer";
const DESCRIPTION =
  "MrVayn builds AAA-caliber game feel in Unreal Engine 5 (gameplay systems, Niagara VFX, multiplayer & netcode) and ships full-stack web apps with Next.js, TypeScript, and Postgres. CTO at a 20-person studio; showcased at IGDC 2025.";


export const metadata: Metadata = {
  metadataBase: new URL(SITE),
  title: {
    default: TITLE,
    template: "%s | MrVayn",
  },
  description: DESCRIPTION,
  keywords: [
    "MrVayn",
    "Unreal Engine developer",
    "Unreal Engine 5",
    "UE5 developer",
    "Niagara VFX",
    "multiplayer netcode",
    "gameplay systems",
    "game developer portfolio",
    "full-stack developer",
    "Next.js developer",
    "TypeScript",
    "React",
  ],
  authors: [{ name: "MrVayn", url: SITE }],
  creator: "MrVayn",
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    url: SITE,
    siteName: "MrVayn",
    title: TITLE,
    description: DESCRIPTION,
    locale: "en_US",
    // OG image is generated by app/opengraph-image.tsx (1200x630).
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large", "max-snippet": -1 },
  },
  icons: {
    icon: [
      { url: "/favicon.svg", type: "image/svg+xml" },
      { url: "/favicon.png", type: "image/png" },
    ],
    apple: "/favicon.png",
  },
  manifest: "/site.webmanifest",
  appleWebApp: { capable: true, title: "MrVayn", statusBarStyle: "black-translucent" },
};

// Structured data: tells Google who MrVayn is + links his profiles (rich results).
const structuredData = [
  {
    "@context": "https://schema.org",
    "@type": "Person",
    name: "MrVayn",
    url: SITE,
    jobTitle: "Unreal Engine & Full-Stack Developer",
    description: DESCRIPTION,
    knowsAbout: [
      "Unreal Engine 5",
      "Niagara VFX",
      "Multiplayer & Netcode",
      "Gameplay Systems",
      "C++",
      "Next.js",
      "TypeScript",
      "React",
      "PostgreSQL",
      "LangChain & RAG",
    ],
    sameAs: socials.flatMap((s) => (s.href ? [s.href] : [])),
  },
  {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: "MrVayn",
    url: SITE,
  },
];

export const viewport: Viewport = {
  themeColor: "#07080B",
  colorScheme: "dark",
};

// Runs before the hero is parsed: tells the CSS whether the boot cinematic will play
// (returning and reduced-motion visitors skip it, so the hero must not double-reveal).
const BOOT_SCRIPT =
  "try{var d=document.documentElement;d.dataset.boot=(matchMedia('(prefers-reduced-motion: reduce)').matches||sessionStorage.getItem('booted')==='1')?'skip':'play'}catch(e){}";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning className={`${grotesk.variable} ${inter.variable} ${jetbrains.variable} ${headline.variable}`}>
      <body className="font-sans antialiased">
        <script dangerouslySetInnerHTML={{ __html: BOOT_SCRIPT }} />
        {children}
        <script
          type="application/ld+json"
          // eslint-disable-next-line react/no-danger
          dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
        />
      </body>
    </html>
  );
}
